jobs:
- job: BuildLinuxWithSonarQube
  displayName: Build for Linux\Autotools With SonarQube
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # Make Build Wrapper available
  - task: Bash@3
    displayName: Download Build Wrapper
    inputs:
      targetType: inline
      script: >
        curl  '<SONARQUBE_HOST>/static/cpp/build-wrapper-linux-x86.zip' --output build-wrapper.zip
        unzip build-wrapper.zip
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'azure-sq'
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties: "sonar.cfamily.build-wrapper-output=bw_output"
  - bash: |
      mkdir build
      cmake -S . -B build
      export PATH=$HOME/.sonar/build-wrapper-linux-x86:$PATH
      autoreconf --install
      ./configure
      build-wrapper-linux-x86-64 --out-dir bw_output make clean all
    workingDirectory: .
    displayName: Build in build-wrapper
  - task: SonarQubeAnalyze@4
